#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import csv
from pathlib import Path

VERSION_STR = 'v0.1.0'
RUST_DIR = Path(__file__).parent
HEBREW_TSV = RUST_DIR / '../sourceTables/Hebrew.tsv'
GREEK_TSV = RUST_DIR / '../sourceTables/Greek.tsv'
RUST_SOURCE = RUST_DIR / 'lib.src.rs'
RUST_OUTPUT = RUST_DIR / 'src/lib.rs'

def load_tsv(path, source_col_name):
    rows = []
    with open(path, 'r', encoding='utf-8') as f:
        # Handle BOM if present
        content = f.read()
        if content.startswith('\ufeff'):
            content = content[1:]
        
        reader = csv.DictReader(content.splitlines(), delimiter='\t')
        for row in reader:
            source = (row.get(source_col_name) or '').strip()
            en = (row.get('en') or '').strip()
            if source:
                rows.append({'source': source, 'en': en})
    
    # Sort by source length (chars) descending. Python's sort is stable, 
    # so this preserves the original file order for equal lengths.
    rows.sort(key=lambda r: -len(r['source']))
    return rows

def format_rust_rows(rows):
    entries = []
    for row in rows:
        # Escape backslashes and quotes for Rust string literals
        source = row['source'].replace('\\', '\\\\').replace('"', '\\"')
        en = row['en'].replace('\\', '\\\\').replace('"', '\\"')
        entries.append(f'    StaticRow {{ source: "{source}", en: "{en}" }},')
    return '\n'.join(entries)

if __name__ == '__main__':
    print(f"Generating static tables {VERSION_STR}...")
    
    hebrew_rows = load_tsv(HEBREW_TSV, 'hbo')
    greek_rows = load_tsv(GREEK_TSV, 'x-grc-koine')
    
    hebrew_static = format_rust_rows(hebrew_rows)
    greek_static = format_rust_rows(greek_rows)
    
    with open(RUST_SOURCE, 'r', encoding='utf-8') as f:
        template = f.read()
    
    # Replace the placeholders
    output = template.replace('//STATIC_STRUCTS_GO_HERE', f'''
pub struct StaticRow {{
    pub source: &'static str,
    pub en: &'static str,
}}

pub static HEBREW_TABLE: &[StaticRow] = &[
{hebrew_static}
];

pub static GREEK_TABLE: &[StaticRow] = &[
{greek_static}
];
''')

    # Ensure the src directory exists
    RUST_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    
    with open(RUST_OUTPUT, 'w', encoding='utf-8') as f:
        f.write(f"// WARNING: DO NOT EDIT THIS FILE!!!\n")
        f.write(f"// This file was automatically generated by build_static_tables.py {VERSION_STR}\n")
        f.write(f"// from the TSV files in sourceTables/ and the template lib.src.rs\n\n")
        f.write(output)
    
    print("SUCCESSFUL! $")
